services:

  mongod:
    image: mongo:latest
    container_name: mongoDB-c
    ports:
      - 27017:27017
    volumes:
      - nova_mongo_data:/data/db
    networks:
      - nova-net

  nginx-mos:
    image: quantumcubed/nginx-http3-quic:latest
    container_name: nginx-mos-c
    env_file:
      - ./.env
    ports:
      - ${PORT_TCP}:8443/TCP
      - ${PORT_UDP}:8443/UDP
    volumes:
    #  - E:\Coding-Stuff\NOVA\backend\go-transcoding-server\content:/dash
    #  - E:\Coding-Stuff\NOVA\backend\nginx-media-origin-server\nginx.conf:/etc/nginx/nginx.conf
    #  - E:\Coding-Stuff\NOVA\backend\nginx-media-origin-server\http.conf:/etc/nginx/conf.d/http.conf
      - ${NGINX_CONF}:/etc/nginx/nginx.conf
      - ${HTTP_CONF}:/etc/nginx/conf.d/http.conf
    #  - E:\Coding-Stuff\NOVA\data:/data
      - nova_data:/data
    networks:
      - nova-net
    depends_on:
      - mongod

  go-mts:
    image: quantumcubed/go-transcoder:latest
    container_name: go-mts-c
    ports:
      - 50051:50051
    volumes:
      - ./go-transcoding-server/:/transcoder
      - nova_data:/data
    networks:
      - nova-net
    depends_on:
      - mongod

  nova-ws:
    image: node
    container_name: nova-ws-c
    ports:
      - 3000:3000
    volumes:
      - ./nodejs-web-server/:/nodejs-web-server
      - nova_data:/data
    working_dir: /nodejs-web-server
    networks:
      - nova-net
    # stdin_open: true   # Equivalent to -i flag
    # tty: true          # Equivalent to -t flag
    command: ["npm", "run", "dev"]
    depends_on:
      - mongod
      - nginx-mos
      - go-mts

volumes:
  nova_data:
    external: true
  nova_mongo_data:
    external: true

networks:
  nova-net:
    external: true