// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: tcServiceProtocol.proto

package transcode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TcReq_TranscodeVideo_FullMethodName = "/transcode.tcReq/transcodeVideo"
)

// TcReqClient is the client API for TcReq service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TcReqClient interface {
	TranscodeVideo(ctx context.Context, in *VidMetaData, opts ...grpc.CallOption) (*TcStatus, error)
}

type tcReqClient struct {
	cc grpc.ClientConnInterface
}

func NewTcReqClient(cc grpc.ClientConnInterface) TcReqClient {
	return &tcReqClient{cc}
}

func (c *tcReqClient) TranscodeVideo(ctx context.Context, in *VidMetaData, opts ...grpc.CallOption) (*TcStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TcStatus)
	err := c.cc.Invoke(ctx, TcReq_TranscodeVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TcReqServer is the server API for TcReq service.
// All implementations must embed UnimplementedTcReqServer
// for forward compatibility.
type TcReqServer interface {
	TranscodeVideo(context.Context, *VidMetaData) (*TcStatus, error)
	mustEmbedUnimplementedTcReqServer()
}

// UnimplementedTcReqServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTcReqServer struct{}

func (UnimplementedTcReqServer) TranscodeVideo(context.Context, *VidMetaData) (*TcStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TranscodeVideo not implemented")
}
func (UnimplementedTcReqServer) mustEmbedUnimplementedTcReqServer() {}
func (UnimplementedTcReqServer) testEmbeddedByValue()               {}

// UnsafeTcReqServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TcReqServer will
// result in compilation errors.
type UnsafeTcReqServer interface {
	mustEmbedUnimplementedTcReqServer()
}

func RegisterTcReqServer(s grpc.ServiceRegistrar, srv TcReqServer) {
	// If the following call pancis, it indicates UnimplementedTcReqServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TcReq_ServiceDesc, srv)
}

func _TcReq_TranscodeVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VidMetaData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcReqServer).TranscodeVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TcReq_TranscodeVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcReqServer).TranscodeVideo(ctx, req.(*VidMetaData))
	}
	return interceptor(ctx, in, info, handler)
}

// TcReq_ServiceDesc is the grpc.ServiceDesc for TcReq service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TcReq_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transcode.tcReq",
	HandlerType: (*TcReqServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "transcodeVideo",
			Handler:    _TcReq_TranscodeVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tcServiceProtocol.proto",
}
