// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: tcServiceProtocol.proto

package transcode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VidMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VidInput string `protobuf:"bytes,1,opt,name=vidInput,proto3" json:"vidInput,omitempty"`
}

func (x *VidMetaData) Reset() {
	*x = VidMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcServiceProtocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VidMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VidMetaData) ProtoMessage() {}

func (x *VidMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_tcServiceProtocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VidMetaData.ProtoReflect.Descriptor instead.
func (*VidMetaData) Descriptor() ([]byte, []int) {
	return file_tcServiceProtocol_proto_rawDescGZIP(), []int{0}
}

func (x *VidMetaData) GetVidInput() string {
	if x != nil {
		return x.VidInput
	}
	return ""
}

type TcStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *TcStatus) Reset() {
	*x = TcStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcServiceProtocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcStatus) ProtoMessage() {}

func (x *TcStatus) ProtoReflect() protoreflect.Message {
	mi := &file_tcServiceProtocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcStatus.ProtoReflect.Descriptor instead.
func (*TcStatus) Descriptor() ([]byte, []int) {
	return file_tcServiceProtocol_proto_rawDescGZIP(), []int{1}
}

func (x *TcStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_tcServiceProtocol_proto protoreflect.FileDescriptor

var file_tcServiceProtocol_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0x29, 0x0a, 0x0b, 0x76, 0x69, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x69, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x22,
	0x22, 0x0a, 0x08, 0x74, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x32, 0x46, 0x0a, 0x05, 0x74, 0x63, 0x52, 0x65, 0x71, 0x12, 0x3d, 0x0a, 0x0e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x16,
	0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x69, 0x64, 0x4d, 0x65,
	0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x13, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f,
	0x64, 0x65, 0x2e, 0x74, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x21, 0x5a, 0x1f, 0x6e,
	0x6f, 0x76, 0x61, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tcServiceProtocol_proto_rawDescOnce sync.Once
	file_tcServiceProtocol_proto_rawDescData = file_tcServiceProtocol_proto_rawDesc
)

func file_tcServiceProtocol_proto_rawDescGZIP() []byte {
	file_tcServiceProtocol_proto_rawDescOnce.Do(func() {
		file_tcServiceProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_tcServiceProtocol_proto_rawDescData)
	})
	return file_tcServiceProtocol_proto_rawDescData
}

var file_tcServiceProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tcServiceProtocol_proto_goTypes = []any{
	(*VidMetaData)(nil), // 0: transcode.vidMetaData
	(*TcStatus)(nil),    // 1: transcode.tcStatus
}
var file_tcServiceProtocol_proto_depIdxs = []int32{
	0, // 0: transcode.tcReq.transcodeVideo:input_type -> transcode.vidMetaData
	1, // 1: transcode.tcReq.transcodeVideo:output_type -> transcode.tcStatus
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tcServiceProtocol_proto_init() }
func file_tcServiceProtocol_proto_init() {
	if File_tcServiceProtocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tcServiceProtocol_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*VidMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tcServiceProtocol_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TcStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tcServiceProtocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tcServiceProtocol_proto_goTypes,
		DependencyIndexes: file_tcServiceProtocol_proto_depIdxs,
		MessageInfos:      file_tcServiceProtocol_proto_msgTypes,
	}.Build()
	File_tcServiceProtocol_proto = out.File
	file_tcServiceProtocol_proto_rawDesc = nil
	file_tcServiceProtocol_proto_goTypes = nil
	file_tcServiceProtocol_proto_depIdxs = nil
}
