# stunnel.conf
pid=/var/run/stunnel/stunnel.pid
#output=/var/log/stunnel/stunnel.log
setuid=stunnel
setgid=stunnel
foreground=yes

[https]
#client=no
# Port for incoming HTTPS requests
accept=0.0.0.0:443
# Varnish HTTP
connect=varnish:80
cert=/etc/stunnel/stunnel.pem